vizzy:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  #
  # Position controllers - TODO: Replace by effort
  #

  # Torso Position Controllers
  waist_position_controller:
    type: velocity_controllers/JointPositionController
    joint: waist_joint
    pid: {p: 100.0, i: 0.0, d: 0.0}

  # Right Hand Position Controllers
  r_min_phal_1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_min_phal_1_joint
    pid: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}

  r_med_phal_1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_med_phal_1_joint
    pid: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}

  r_ind_phal_1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_ind_phal_1_joint
    pid: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}

  r_thumb_phal_1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_thumb_phal_1_joint
    pid: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}

  r_thumb_phal_2_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_thumb_phal_2_joint
    pid: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}

  # Head Position Controllers
  neck_pan_position_controller:
    type: velocity_controllers/JointPositionController
    joint: neck_pan_joint
    pid: {p: 100.0, i: 0.01, d: 0.01}

  neck_tilt_position_controller:
    type: velocity_controllers/JointPositionController
    joint: neck_tilt_joint
    pid: {p: 100.0, i: 0.01, d: 0.01}

  eyes_tilt_position_controller:
    type: velocity_controllers/JointPositionController
    joint: eyes_tilt_joint
    pid: {p: 100.0, i: 0.01, d: 0.01}

  l_eye_position_controller:
    type: velocity_controllers/JointPositionController
    joint: l_eye_joint
    pid: {p: 50.0, i: 0.1, d: 0.1, i_clamp: 1.0}

  r_eye_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_eye_joint
    pid: {p: 50.0, i: 0.1, d: 0.1, i_clamp: 1.0}

  # Left arm Position Controllers
  l_shoulder_scapula_position_controller:
    type: velocity_controllers/JointPositionController
    joint: l_shoulder_scapula_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  l_shoulder_flection_position_controller:
    type: velocity_controllers/JointPositionController
    joint: l_shoulder_flection_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  l_shoulder_rotation_position_controller:
    type: velocity_controllers/JointPositionController
    joint: l_shoulder_rotation_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  l_elbow_flection_position_controller:
    type: velocity_controllers/JointPositionController
    joint: l_elbow_flection_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  l_forearm_pronation_position_controller:
    type: velocity_controllers/JointPositionController
    joint: l_forearm_pronation_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  l_wrist_abduction_position_controller:
    type: velocity_controllers/JointPositionController
    joint: l_wrist_abduction_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  l_wrist_flection_position_controller:
    type: velocity_controllers/JointPositionController
    joint: l_wrist_flection_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  # Right arm Position Controllers
  r_shoulder_scapula_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_shoulder_scapula_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  r_shoulder_flection_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_shoulder_flection_joint
    pid: {p: 1.0, i: 0.01, d: 0}

  r_shoulder_rotation_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_shoulder_rotation_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  r_elbow_flection_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_elbow_flection_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  r_forearm_pronation_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_forearm_pronation_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  r_wrist_abduction_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_wrist_abduction_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  r_wrist_flection_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_wrist_flection_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  #
  # Trajectory Controllers
  #
  head_trajectory_controller:
    type: velocity_controllers/JointTrajectoryController
    joints:
      - neck_pan_joint
      - neck_tilt_joint
      - eyes_tilt_joint
    gains:
      neck_pan_joint:
        p: 3.0
        i: 0.01
        d: 0.01
      neck_tilt_joint:
        p: 10.0
        i: 0.01
        d: 0.01
      eyes_tilt_joint:
        p: 10.0
        i: 0.1
        d: 0.1
    constraints:
      goal_time: 10.0                   # Override default
      neck_pan_joint:
        trajectory: -1.0
        goal: 0.0004
      neck_tilt_joint:
        trajectory: -1.0
        goal: 0.0004
      eyes_tilt_joint:
        trajectory: -1.0
        goal: 0.0004

  eyes_trajectory_controller:
    type: velocity_controllers/JointTrajectoryController
    joints:
    - l_eye_joint
    - r_eye_joint
    gains:
      l_eye_joint:
        p: 3.0
        i: 0.001
        d: 0.001
        i_clamp: 1.0
      r_eye_joint:
        p: 3.0
        i: 0.001
        d: 0.001
        i_clamp: 1.0
    constraints:
      goal_time: 10.0                   # Override default
      stopped_velocity_tolerance: 0.00001
      l_eye_joint:
        trajectory: -1.0
        goal: 0.0004
      r_eye_joint:
        trajectory: -1.0
        goal: 0.0004


  oculocephalic_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
    - neck_pan_joint
    - neck_tilt_joint
    - eyes_tilt_joint
    - l_eye_joint
    - r_eye_joint
    gains:
      neck_pan_joint:
        p: 50.0
        i: 0.01
        d: 0.01
      neck_tilt_joint:
        p: 50.0
        i: 0.01
        d: 0.01
      eyes_tilt_joint:
        p: 50.0
        i: 0.1
        d: 0.1
      l_eye_joint:
        p: 5.0
        i: 0.001
        d: 0.001
        i_clamp: 1.0
      r_eye_joint:
        p: 5.0
        i: 0.001
        d: 0.001
    constraints:
      goal_time: 10.0                   # Override default
      stopped_velocity_tolerance: 0.00001
      neck_pan_joint:
        trajectory: -1.0
        goal: 0.0004
      neck_tilt_joint:
        trajectory: -1.0
        goal: 0.0004
      eyes_tilt_joint:
        trajectory: -1.0
        goal: 0.0004
      l_eye_joint:
        trajectory: -1.0
        goal: 0.0004
      r_eye_joint:
        trajectory: -1.0
        goal: 0.0004


  left_arm_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - l_shoulder_scapula_joint
      - l_shoulder_flection_joint
      - l_shoulder_abduction_joint
      - l_shoulder_rotation_joint
      - l_elbow_flection_joint
      - l_forearm_pronation_joint
      - l_wrist_abduction_joint
      - l_wrist_flection_joint
    gains:
      l_shoulder_scapula_joint:
        p: 500.0
        i: 0.0
        d: 0.0
      l_shoulder_flection_joint:
        p: 500.0
        i: 0.0
        d: 0.0
      l_shoulder_abduction_joint:
        p: 100.0
        i: 0.0
        d: 0.0
      l_shoulder_rotation_joint:
        p: 100.0
        i: 0.0
        d: 0.0
      l_elbow_flection_joint:
        p: 100.0
        i: 0.0
        d: 0.0
      l_forearm_pronation_joint:
        p: 100.0
        i: 0.0
        d: 0.0
      l_wrist_abduction_joint:
        p: 100.0
        i: 0.0
        d: 0.0
      l_wrist_flection_joint:
        p: 100.0
        i: 0.0
        d: 0.0
    constraints:
      goal_time: 1000.0                   # Override default
      l_shoulder_scapula_joint:
        trajectory: -1.0
        goal: 0
      l_shoulder_flection_joint:
        trajectory: -1.0
        goal: 0
      l_shoulder_abduction_joint:
        trajectory: -1.0
        goal: 0
      l_shoulder_rotation_joint:
        trajectory: -1.0
        goal: 0
      l_elbow_flection_joint:
        trajectory: -1.0
        goal: 0
      l_forearm_pronation_joint:
        trajectory: -1.0
        goal: 0
      l_wrist_abduction_joint:
        trajectory: -1.0
        goal: 0
      l_wrist_flection_joint:
        trajectory: -1.0
        goal: 0

  right_arm_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - r_shoulder_scapula_joint
      - r_shoulder_flection_joint
      - r_shoulder_abduction_joint
      - r_shoulder_rotation_joint
      - r_elbow_flection_joint
      - r_forearm_pronation_joint
      - r_wrist_abduction_joint
      - r_wrist_flection_joint
    gains:
      r_shoulder_scapula_joint:
        p: 500.0
        i: 0.1
        d: 0.1
      r_shoulder_flection_joint:
        p: 500.0
        i: 0.1
        d: 0.1
      r_shoulder_abduction_joint:
        p: 100.0
        i: 0.1
        d: 0.1
      r_shoulder_rotation_joint:
        p: 100.0
        i: 0.1
        d: 0.1
      r_elbow_flection_joint:
        p: 100.0
        i: 0.1
        d: 0.1
      r_forearm_pronation_joint:
        p: 100.0
        i: 0.1
        d: 0.1
      r_wrist_abduction_joint:
        p: 100.0
        i: 0.1
        d: 0.1
      r_wrist_flection_joint:
        p: 100.0
        i: 0.1
        d: 0.1
    constraints:
      goal_time: 1000.0                   # Override default
      r_shoulder_scapula_joint:
        trajectory: -1.0
        goal: 0
      r_shoulder_flection_joint:
        trajectory: -1.0
        goal: 0
      r_shoulder_abduction_joint:
        trajectory: -1.0
        goal: 0
      r_shoulder_rotation_joint:
        trajectory: -1.0
        goal: 0
      r_elbow_flection_joint:
        trajectory: -1.0
        goal: 0
      r_forearm_pronation_joint:
        trajectory: -1.0
        goal: 0
      r_wrist_abduction_joint:
        trajectory: -1.0
        goal: 0
      r_wrist_flection_joint:
        trajectory: -1.0
        goal: 0
