vizzy:

  # Right Hand Position Controllers
  r_min_phal_1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_min_phal_1_joint
    pid: {p: 5.0, i: 0.0, d: 0.0}
  r_min_phal_2_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_min_phal_2_joint
    pid: {p: 5.0, i: 0.0, d: 0.0}
  r_min_phal_3_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_min_phal_3_joint
    pid: {p: 5.0, i: 0.0, d: 0.0}

  r_med_phal_1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_med_phal_1_joint
    pid: {p: 5.0, i: 0.0, d: 0.0}
  r_med_phal_2_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_med_phal_2_joint
    pid: {p: 5.0, i: 0.0, d: 0.0}
  r_med_phal_3_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_med_phal_3_joint
    pid: {p: 5.0, i: 0.0, d: 0.0}

  r_ind_phal_1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_ind_phal_1_joint
    pid: {p: 100.0, i: 0.0, d: 0.0}
  r_ind_phal_2_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_ind_phal_2_joint
    pid: {p: 100.0, i: 0.0, d: 0.0}
  r_ind_phal_3_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_ind_phal_3_joint
    pid: {p: 100.0, i: 0.0, d: 0.0}

  r_thumb_phal_1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_thumb_phal_1_joint
    pid: {p: 100.0, i: 0.0, d: 0.0}
  r_thumb_phal_2_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_thumb_phal_2_joint
    pid: {p: 100.0, i: 0.0, d: 0.0}
  r_thumb_phal_3_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_thumb_phal_3_joint
    pid: {p: 100.0, i: 0.0, d: 0.0}