vizzy:

  # Right Hand Position Controllers

  r_med_phal_1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_med_phal_1_joint
    pid: {p: 2.0, i: 0.0, d: 0.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}

  r_ind_phal_1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_ind_phal_1_joint
    pid: {p: 2.0, i: 0.0, d: 0.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}

  r_thumb_phal_1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: r_thumb_phal_1_joint
    pid: {p: 2.0, i: 0.0, d: 0.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
