controller_list:
  - name: fake_head_controller
    joints:
      - neck_pan_joint
      - neck_tilt_joint
      - eyes_tilt_joint
  - name: fake_eyes_controller
    joints:
      - vergence_joint
      - version_joint
  - name: fake_oculocephalic_controller
    joints:
      - neck_pan_joint
      - neck_tilt_joint
      - eyes_tilt_joint
      - vergence_joint
      - version_joint
  - name: fake_right_arm_controller
    joints:
      - r_shoulder_scapula_joint
      - r_shoulder_flection_joint
      - r_shoulder_abduction_joint
      - r_shoulder_rotation_joint
      - r_elbow_flection_joint
      - r_forearm_pronation_joint
      - r_wrist_abduction_joint
      - r_wrist_flection_joint