scan_filter_chain:
- name: nan_to_inf_filter
  type: vizzy_sensors/NanToInfFilter
- name: footprint_filter
  type: vizzy_sensors/VizzyFootprintFilter
  params:
    footprint_frame: base_footprint
    footprint: [0.2,0.5,0.2,-0.5,-0.5,-0.5,-0.5,0.5]
