<?xml version="1.0"?>
<robot  name="vizzy" xmlns:xacro="http://ros.org/wiki/xacro" >

  <!-- The following include files set up definitions of parts of the robot body  -->
  <!-- misc common stuff -->
  <xacro:include filename="$(find vizzy_description)/urdf/common.urdf.xacro" />
  <!-- sensors -->
  <xacro:include filename="$(find vizzy_description)/urdf/mounts/hokuyo_mount.urdf.xacro" />
  <!-- base -->
  <xacro:include filename="$(find vizzy_description)/urdf/base/base.urdf.xacro" />
  <!-- torso -->
  <xacro:include filename="$(find vizzy_description)/urdf/torso/torso.urdf.xacro" />
  <!-- head -->


  <xacro:include filename="$(find vizzy_description)/urdf/head/head.yarp.urdf.xacro" />


  <!-- left arm -->
  <xacro:include filename="$(find vizzy_description)/urdf/arm/left_arm.urdf.xacro" />
  <!-- right arm -->
  <xacro:include filename="$(find vizzy_description)/urdf/arm/right_arm.urdf.xacro" />
	<!-- The following include files contain gazebo plugins -->
  <!-- ROS -->
  <xacro:include filename="$(find vizzy_description)/plugins/ros.gazebo.xacro" />
  <!-- Yarp -->
  <xacro:include filename="$(find vizzy_description)/plugins/yarp.gazebo.xacro" />

  <!-- instantiate base -->
  <xacro:base name="base"/>
  <!-- instantiate torso -->
  <xacro:torso name="torso"/>
  <!-- instantiate head -->
  <xacro:head name="head"/>
  <!-- instantiate left arm -->
  <xacro:left_arm name="left_arm" parent="waist_link" sufix="l" reflect="1">
    <origin xyz="-0.01707 0.0 0.38145" rpy="0.0 0.0 0.0" />
  </xacro:left_arm>
  <!-- instantiate right arm -->
  <xacro:right_arm name="right_arm" parent="waist_link" sufix="r" reflect="1">
    <origin xyz="-0.01707 0.0 0.38145" rpy="0.0 0.0 0.0" />
  </xacro:right_arm>

  <!-- instantiate hokuyo -->
  <xacro:hokuyo_mount name="nav_hokuyo" parent="base" length="${SENSOR_BEAM_LENGTH*INCH_TO_M}" ros_topic="scan" update_rate="10" min_angle="${-(5 * M_PI)/12}" max_angle="${(5 * M_PI)/12}">
    <origin xyz="-0.05 0.14 0.15" rpy="${-M_PI/2} ${-M_PI/2} 3.14" />
  </xacro:hokuyo_mount>

  <!-- instantiate common ROS and Yarp plugins -->
  <xacro:ros_differential_drive_gazebo/>
  <xacro:camera_plugin name="l_camera" prefix="l"/>
  <xacro:camera_plugin name="r_camera" prefix="r"/>

  <!-- instantiate Yarp plugins -->
  <xacro:torso_gazebo_control/>
  <xacro:head_gazebo_control/>
  <xacro:left_arm_gazebo_control/>
  <xacro:right_arm_gazebo_control/>


</robot>
